# -*- coding: utf-8 -*-
"""Matheus Ferreira Carneiro - Compiladores 2024/1 - Projeto 1: Simulação de SAM.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WmGW76tGC-HAj2Xh19ugXPHWiHxKc7sA


"""

from lexical import *
from commands import *



"""## O programa

Quando o programa abaixo rodar, ele irá receber o nome do arquivo a ser rodado
"""

arquivo_nome = input('Envie o nome do arquivo: ')

program = []
stack = []
fbr = 0
sp = 0

labels = {}


with open(arquivo_nome, 'r') as arquivo:
  for linha in arquivo:
    indice = 0
    prog_linha = ler_linha(linha, indice)
    if not prog_linha:
      pass
    elif prog_linha['Tipo'] == 'Label':
      labels[prog_linha['Nome']] = indice
    else:
      program.append(prog_linha)
      indice += 1

"""## Teste

"""

program = [
    {'Nome' : 'ADDSP', 'Tipo' : 'Stack/Heap Allocation', 'Endereco' : 0, 'Valor': 6},
    {'Nome' : 'PUSHIMM', 'Tipo' : 'Stack Insertion',  'Endereco' : 1, 'Valor': -10},
    {'Nome' : 'PUSHIMM', 'Tipo' : 'Stack Insertion',  'Endereco' : 2, 'Valor': 0},
    {'Nome' : 'PUSHIMM', 'Tipo' : 'Stack Insertion',  'Endereco' : 3, 'Valor': 10},
    {'Nome' : 'PUSHABS', 'Tipo' : 'Absolute Store/Retrieve',  'Endereco' : 4, 'Valor': 7},
    {'Nome' : 'ISNIL', 'Tipo' : 'Comparison', 'Endereco' : 5},
    {'Nome' : 'STOREABS', 'Tipo' : 'Absolute Store/Retrieve',  'Endereco' : 6, 'Valor': 0},
    {'Nome' : 'PUSHABS', 'Tipo' : 'Absolute Store/Retrieve',  'Endereco' : 7, 'Valor': 8},
    {'Nome' : 'ISNIL', 'Tipo' : 'Comparison', 'Endereco' : 8},
    {'Nome' : 'STOREABS', 'Tipo' : 'Absolute Store/Retrieve',  'Endereco' : 9, 'Valor': 1},
    {'Nome' : 'PUSHABS', 'Tipo' : 'Absolute Store/Retrieve',  'Endereco' : 10, 'Valor': 6},
    {'Nome' : 'ISPOS', 'Tipo' : 'Comparison', 'Endereco' : 11},
    {'Nome' : 'STOREABS', 'Tipo' : 'Absolute Store/Retrieve',  'Endereco' : 12, 'Valor': 2},
    {'Nome' : 'PUSHABS', 'Tipo' : 'Absolute Store/Retrieve',  'Endereco' : 13, 'Valor': 8},
    {'Nome' : 'ISPOS', 'Tipo' : 'Comparison', 'Endereco' : 14},
    {'Nome' : 'STOREABS', 'Tipo' : 'Absolute Store/Retrieve',  'Endereco' : 15, 'Valor': 3},
    {'Nome' : 'PUSHABS', 'Tipo' : 'Absolute Store/Retrieve',  'Endereco' : 16, 'Valor': 6},
    {'Nome' : 'ISNEG', 'Tipo' : 'Comparison', 'Endereco' : 17},
    {'Nome' : 'STOREABS', 'Tipo' : 'Absolute Store/Retrieve',  'Endereco' : 18, 'Valor': 4},
    {'Nome' : 'PUSHABS', 'Tipo' : 'Absolute Store/Retrieve',  'Endereco' : 19, 'Valor': 8},
    {'Nome' : 'ISNEG', 'Tipo' : 'Comparison', 'Endereco' : 20},
    {'Nome' : 'STOREABS', 'Tipo' : 'Absolute Store/Retrieve',  'Endereco' : 21, 'Valor': 5},
    {'Nome' : 'ADDSP', 'Tipo' : 'Stack/Heap Allocation', 'Endereco' : 22, 'Valor': -3}
]
stack = []
fbr = 0
sp = 0
halt = 0

for comando in program:
  fbr, sp, halt = detect_comando(program, labels, fbr, stack, sp, halt)
  fbr += 1

print(program)
print(stack)
print(fbr)
print(sp)
print(halt)